# Generated by Django 3.0.3 on 2020-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
