# Generated by Django 3.0.3 on 2020-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200812_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='PostImage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
